---
title: "Leadership and Community Engagement"
---

### Vice President, Minoritized Genders in Natural Resources 

Member since Fall ‘24 Vice President, December ‘24 - Present

Led and organized community-building events, such as the Women + Minoritized Genders Forest Congress and OneCanopy Volunteer event, fostering inclusivity and diversity within natural resources. - Planned and tabled multiple outreach events while developing and submitting grant applications to secure funding, enhancing support and visibility for minoritized groups in the field.

### Mentor, ENGAGE Scholars, Warner College of Natural Resources 

Fall ‘23 - Present

Mentored incoming students, providing guidance on academic and career goals while enhancing peer connections and supporting their success in sustainability studies. - Advised students in weekly meetings ranging from 3 to 10 hours, providing guidance, support, and academic development.

### Member & Past Officer, Xi Sigma Pi Honor’s Society- Omicron Chapter 

February ‘23-Present

Contributed to chapter activities and leadership initiatives, supporting academic excellence and fostering professional development within natural resources; served as an Officer in Spring ‘24 to drive community engagement and strategic planning. ---
